backend:
  name: git-gateway
  branch: master

media_folder: "img/uploads"

collections:
  - name: "publicaciones"
    label: "Publicaciones"
    folder: "_posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}

  - name: "pages"
    label: "Pages"
    files:
      - label: "Home"
        name: "home"
        file: "index.md"
        fields:
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Body", name: "body", widget: "markdown"}
