backend:
  name: git-gateway
  branch: master

publish_mode: editorial_workflow

media_folder: "img/uploads"

pages:
  markdown:
    extra: true

collections:
  - name: "publicaciones"
    label: "Publicaciones"
    folder: "_posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "layout", name: "Layout", widget: "hidden", post: "publicaciones"}
      - {label: "Título", name: "title", widget: "string"}
      - {label: "Fecha", name: "Publicado el", widget: "datetime"}
      - {label: "Publicado por", name: "author", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Imagen", name: "image", widget: "image", required: false}

  - name: "pages"
    label: "Pages"
    files:
      - label: "About"
        name: "about"
        file: "about.md"
        fields:
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Body", name: "body", widget: "markdown"}

      - label: "Home"
        name: "home"
        file: "index.md"
        fields:
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Body", name: "body", widget: "markdown"}
