backend:
  name: git-gateway
  branch: master

media_folder: "img/uploads"

collections:
  - name: "publicaciones"
    label: "Publicaciones"
    folder: "_posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}

  - name: "pages"
    label: "Pages"
    files:
      - label: "Home"
        name: "home"
        file: "index.html"
        fields:
          - {label: "Body", name: "body", widget: "markdown"}

      - label: "Beca"
        name: "beca"
        file: "beca.html"
        fields:
          - {label: "Body", name: "body", widget: "markdown"}

      - label: "Oferta"
        name: "oferta"
        file: "oferta.html"
        fields:
          - {label: "Body", name: "body", widget: "markdown"}

  - name: "settings"
    label: "Settings"
    files:
      - label: "Actividades"
        name: "actividades"
        file: "_data/actividades.yml"
        fields:
          - label: "Content"
            name: "content"
            widget: "markdown"

      - label: "Viajes Baler 2017"
        name: "viajes_baler2017"
        file: "_data/viajes_baler2017.yml"
        fields:
          - label: "Content"
            name: "content"
            widget: "markdown"

      - label: "Viajes Majayjay"
        name: "viajes_majayjay"
        file: "_data/viajes_majayjay.yml"
        fields:
          - label: "Content"
            name: "content"
            widget: "markdown"
