backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

  # This line should *not* be indented
publish_mode: editorial_workflow

# This line should *not* be indented
media_folder: "img/uploads" # Media files will be stored in the repo under images/uploads

collections:
  - name: "publicaciones" # Used in routes, e.g., /admin/collections/blog
    label: "Publicaciones" # Used in the UI
    folder: "_posts" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "layout", name: "Layout", widget: "hidden", post: "publicaciones"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "date", name: "Publicado el", widget: "datetime"}
      - {label: "Publicado por", name: "author", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}